# Generated by Django 5.0.6 on 2024-08-08 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumAct', models.IntegerField(auto_created=True)),
                ('NomAct', models.CharField(blank=True, max_length=150, null=True)),
                ('PostnomAct', models.CharField(blank=True, max_length=150, null=True)),
                ('PrenAct', models.CharField(blank=True, max_length=150, null=True)),
                ('TelAct', models.CharField(blank=True, max_length=150, null=True)),
                ('EmailAct', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeCategcl', models.IntegerField(auto_created=True)),
                ('LibCategcl', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumConsult', models.IntegerField(auto_created=True)),
                ('Date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeNatcl', models.IntegerField(auto_created=True)),
                ('LibNatcl', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nature_consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeNatur', models.IntegerField(auto_created=True)),
                ('DenomNatur', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatricAvoc', models.IntegerField()),
                ('NomAct', models.CharField(blank=True, max_length=150, null=True)),
                ('PostnomAct', models.CharField(blank=True, max_length=150, null=True)),
                ('PrenAct', models.CharField(blank=True, max_length=150, null=True)),
                ('TelAct', models.CharField(blank=True, max_length=150, null=True)),
                ('EmailAct', models.CharField(blank=True, max_length=150, null=True)),
                ('NumAct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActAvoc', to='App.acteur')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCleint', models.IntegerField(auto_created=True)),
                ('EtatciviCleint', models.CharField(blank=True, max_length=20, null=True)),
                ('NomClient', models.CharField(blank=True, max_length=150, null=True)),
                ('PostnomClient', models.CharField(blank=True, max_length=150, null=True)),
                ('PrenonCient', models.CharField(blank=True, max_length=150, null=True)),
                ('LieunClient', models.CharField(blank=True, max_length=150, null=True)),
                ('etaClient', models.CharField(blank=True, max_length=150, null=True)),
                ('NumClien', models.IntegerField()),
                ('Numrccm', models.IntegerField()),
                ('QualClient', models.CharField(blank=True, max_length=150, null=True)),
                ('FaxClient', models.IntegerField()),
                ('Date_create', models.DateTimeField(auto_now_add=True)),
                ('CodeCategcl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categcl', to='App.categorie_client')),
                ('NumAct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActClient', to='App.acteur')),
                ('CodeNatcl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NatClient', to='App.nationalite')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumDoss', models.IntegerField(auto_created=True)),
                ('ElemDoss', models.CharField(blank=True, max_length=150, null=True)),
                ('AttentDoss', models.CharField(blank=True, max_length=150, null=True)),
                ('AvisDoss', models.CharField(blank=True, max_length=150, null=True)),
                ('Date_create', models.DateTimeField(auto_now_add=True)),
                ('Numclient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DosCleint', to='App.client')),
            ],
        ),
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remarquer', models.CharField(blank=True, max_length=150, null=True)),
                ('NumConsult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ConsuConcer', to='App.consultation')),
                ('NumDoss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DosConcer', to='App.dossier')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='CodeNatur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NaturConsult', to='App.nature_consultation'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumPaiem', models.IntegerField(auto_created=True)),
                ('MontPaiem', models.IntegerField()),
                ('MotifPaiem', models.CharField(blank=True, max_length=150, null=True)),
                ('NumCleint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaiemCleint', to='App.client')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='NumPaiem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaiemConsult', to='App.paiement'),
        ),
        migrations.CreateModel(
            name='Rendez_vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumRendez', models.IntegerField(auto_created=True)),
                ('MotifRendez', models.CharField(blank=True, max_length=150, null=True)),
                ('HeureRendez', models.TimeField()),
                ('ObserRendez', models.CharField(blank=True, max_length=150, null=True)),
                ('MatriAvoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RdvAvoc', to='App.avocat')),
                ('NumClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RdvCleint', to='App.client')),
            ],
        ),
    ]
