# Generated by Django 5.0.6 on 2024-08-11 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acteur',
            name='NumAct',
            field=models.IntegerField(auto_created=True, default=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='NumPaiem',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaiemConsult', to='App.paiement'),
        ),
    ]
