# Generated by Django 5.0.6 on 2024-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_acteur_numact_alter_consultation_numpaiem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='NumCleint',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
