# Generated by Django 5.0.6 on 2024-08-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_client_numcleint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='NumCleint',
            field=models.IntegerField(auto_created=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='NumDoss',
            field=models.IntegerField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='nationalite',
            name='CodeNatcl',
            field=models.IntegerField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='NumPaiem',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
