# Generated by Django 5.0.6 on 2024-08-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_client_numcleint_alter_dossier_numdoss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='FaxClient',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='NumClien',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='Numrccm',
            field=models.IntegerField(null=True),
        ),
    ]
