# Generated by Django 5.0.6 on 2024-08-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_client_numcleint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='CodeCategcl',
        ),
        migrations.RemoveField(
            model_name='client',
            name='CodeNatcl',
        ),
        migrations.RemoveField(
            model_name='client',
            name='NumAct',
        ),
    ]
