# Generated by Django 5.0.6 on 2024-08-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_client_codecategcl_remove_client_codenatcl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='CodeCategcl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categcl', to='App.categorie_client'),
        ),
        migrations.AddField(
            model_name='client',
            name='CodeNatcl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NatClient', to='App.nationalite'),
        ),
        migrations.AddField(
            model_name='client',
            name='NumAct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActClient', to='App.acteur'),
        ),
        migrations.AlterField(
            model_name='client',
            name='NumCleint',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
