# Generated by Django 5.0.6 on 2024-08-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_client_codecategcl_client_codenatcl_client_numact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='NumCleint',
        ),
    ]
