# Generated by Django 5.0.6 on 2024-08-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_client_codecategcl_remove_client_codenatcl_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
    ]
