# Generated by Django 5.0.6 on 2024-08-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_rename_client_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='FaxClient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
