# Generated by Django 5.0.6 on 2024-08-12 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_cliente_faxclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrenonCient', models.CharField(blank=True, max_length=150, null=True)),
                ('NomClient', models.CharField(blank=True, max_length=150, null=True)),
                ('PostnomClient', models.CharField(blank=True, max_length=150, null=True)),
                ('LieunClient', models.CharField(blank=True, max_length=150, null=True)),
                ('etaClient', models.CharField(blank=True, max_length=150, null=True)),
                ('EtatciviCleint', models.CharField(blank=True, max_length=20, null=True)),
                ('NumClien', models.IntegerField(blank=True, null=True)),
                ('Numrccm', models.IntegerField(blank=True, null=True)),
                ('QualClient', models.CharField(blank=True, max_length=150, null=True)),
                ('FaxClient', models.CharField(blank=True, max_length=150, null=True)),
                ('Date_create', models.DateTimeField(auto_now_add=True)),
                ('CodeCategcl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Categcl', to='App.categorie_client')),
                ('CodeNatcl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NatClient', to='App.nationalite')),
                ('NumAct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActClient', to='App.acteur')),
            ],
        ),
        migrations.AlterField(
            model_name='dossier',
            name='Numclient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DosCleint', to='App.client'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='NumCleint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PaiemCleint', to='App.client'),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='NumClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RdvCleint', to='App.client'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
