# Generated by Django 5.0.6 on 2024-08-13 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_client_alter_dossier_numclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='NumAvocat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AvocDos', to='App.avocat'),
        ),
    ]
