# Generated by Django 5.0.6 on 2024-08-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_dossier_numavocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
