# Generated by Django 5.0.6 on 2024-08-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_dossier_numdoss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendez_vous',
            name='NumRendez',
        ),
    ]
