# Generated by Django 5.0.6 on 2024-09-03 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_remove_rendez_vous_numrendez'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='Date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
