# Generated by Django 5.0.6 on 2024-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_paiement_date_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='Date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
