# Generated by Django 5.0.6 on 2024-09-09 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_model_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acteur',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_acteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avocat',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_avocat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossier',
            name='consulter',
            field=models.BooleanField(default=False),
        ),
    ]
