# Generated by Django 5.0.6 on 2024-09-10 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_acteur_utilisateur_avocat_utilisateur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvoDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ElemDoss', models.CharField(blank=True, max_length=150, null=True)),
                ('AttentDoss', models.CharField(blank=True, max_length=150, null=True)),
                ('AvisDoss', models.CharField(blank=True, max_length=150, null=True)),
                ('Date_create', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('consulter', models.BooleanField(default=False)),
                ('NumAvocat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EvoAvocDos', to='App.avocat')),
                ('Numclient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EvoDosCleint', to='App.client')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_evo', to='App.dossier')),
            ],
        ),
    ]
