# Generated by Django 5.0.6 on 2024-09-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_dossier_annuler_dossier_traiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='NumCleint',
        ),
        migrations.AddField(
            model_name='paiement',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dossier_paie', to='App.dossier'),
        ),
    ]
