# Generated by Django 5.0.6 on 2024-08-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='AttentDoss',
            new_name='NomClient',
        ),
        migrations.AddField(
            model_name='client',
            name='PostnomClient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='PrenonCient',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='telClien',
            field=models.IntegerField(default='nex colum'),
            preserve_default=False,
        ),
    ]
